// THEME TYPES

export const DEFAULT_THEME = "DEFAULT_THEME";
export const CHANGE_THEME = "CHANGE_THEME";

// BOOK TYPES
export const FETCH_BOOKS_STARTED = "FETCH_BOOKS_STARTED";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
